import {savedGedcom,readView,saveView} from './storage.js?v=04a44ecce2d9';
import {routeLocal,pathData,labelSegment,associationLabel,bridgePaths,routingPlan,associationKey,associationRoute,optimizeFamilyLanes} from './routing.js?v=e078423fbbf2';
import {parseGedcom,dateRu,dateSortKey,lifespan,relatives,relationships,layout,privacyVisible,unconfirmedAncestry,directWithGodparents,isGodparentRelation,EVENT_LABELS,spouseLabel} from './genealogy.js?v=858317a70f69';
import {demo} from './demo.js?v=fe30088a95e8';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,focus,sets,relations,graph,onlyDirect=false,showGodparents=false,hidePrivate=false,verticalBranches=false,opened=null,isDemo=true,filename='',camera={x:0,y:0,k:1},toastTimer,cameraAnimation=0;
let restoring=true;
const measure=document.createElement('canvas').getContext('2d');
function wrap(text,width,font){measure.font=font;const lines=[];let line='';for(const word of String(text).split(/\s+/)){if(measure.measureText(word).width>width){if(line){lines.push(line);line='';}let part='';for(const c of word){if(measure.measureText(part+c).width>width){lines.push(part);part='';}part+=c;}line=part;}else if(measure.measureText(line+(line?' ':'')+word).width>width){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
const privateHidden=id=>hidePrivate&&data.people.get(id)?.private&&!graph?.nodes.has(id);
const shownName=id=>privateHidden(id)?'Личные данные скрыты':data.people.get(id)?.name||'Имя не указано';
const shownLifespan=p=>hidePrivate?(privateHidden(p.id)?'':lifespan({...p,events:p.events.filter(e=>!e.private)})):lifespan(p);
function load(text,name,sample=false){const parsed=parseGedcom(text);data=parsed;filename=name;isDemo=sample;focus=[...data.people.values()].find(p=>/Александр/i.test(p.name)&&/Олегович/i.test(p.name)&&/Сим(?:\s|$)/i.test(p.name))?.id||(sample?'@I13@':data.people.keys().next().value);onlyDirect=false;showGodparents=false;hidePrivate=false;verticalBranches=false;opened=null;$('details').hidden=true;$('search').value='';$('search-results').hidden=true;$('filename').textContent=name;$('source-description').textContent=sample?'Вымышленные данные · попробуйте':`${data.people.size} людей · ${data.families.length} семей · на вашем устройстве`;$('sample-badge').textContent=sample?'ДЕМОНСТРАЦИОННОЕ ДРЕВО':'ЛИЧНЫЙ СЕМЕЙНЫЙ АРХИВ';recalculate();fit();if(data.warnings.length)toast(`Файл открыт. Замечаний к данным: ${data.warnings.length}. Они доступны в сведениях о человеке.`);}
function recalculate(){sets=relatives(data,focus);relations=relationships(data,focus,sets);render();}
function render(){
 const directView=onlyDirect&&showGodparents?directWithGodparents(data,sets.direct):null,candidates=onlyDirect?(directView?.visible||sets.direct):new Set(data.people.keys()),visible=hidePrivate?privacyVisible(data,candidates,focus):candidates;graph=layout(data,visible,sets,{verticalBranches,directMode:onlyDirect,associationAnchors:directView?.detachedAnchors});
 // Allow full names and exact dates to determine height; all cards in a generation share a centre line.
 const rowH=new Map();for(const n of graph.nodes.values()){const p=data.people.get(n.id),hidden=privateHidden(n.id);n.privacyHidden=hidden;n.nameLines=wrap(shownName(n.id),n.w-34,`${n.direct?17:14}px Georgia`);n.variantLines=hidden?[]:p.nameVariants.flatMap(text=>wrap(text,n.w-34,`${n.direct?12:11}px Arial`));n.dateLines=wrap(shownLifespan(p),n.w-34,`${n.direct?12:11}px Arial`);n.relationLabel=hidden?'ЛИЧНАЯ ЗАПИСЬ':n.id===focus?'ВЫБРАННЫЙ ЧЕЛОВЕК':relations.labels.get(n.id);n.relationLines=wrap(n.relationLabel,n.w-28,`${n.id===focus?9:11}px Arial`);n.h=Math.max(n.h,38+n.nameLines.length*(n.direct?22:19)+(n.variantLines.length?4+n.variantLines.length*15:0)+n.dateLines.length*16+n.relationLines.length*14+14);rowH.set(n.rank,Math.max(rowH.get(n.rank)||0,n.h));}
 const plan=routingPlan(data,graph.nodes,rowH),rowY=plan.rowY,unconfirmed=unconfirmedAncestry(data,sets.direct);
 graph.bounds.h=plan.height+140;graph.bounds.y=-100;
 const lines=[],cards=[],edgeLabels=[],edgeRecords=[],markers=[];let edgeIndex=0,labelIndex=0,edgeOwner='';
 const below=n=>plan.laneY(n.rank,edgeOwner);
 const above=n=>plan.laneY(n.rank-1,edgeOwner);
 const port=(n,side)=>plan.portX(n,side,edgeOwner);
 const route=(a,b)=>routeLocal(a,b,graph.nodes,edgeIndex,edgeRecords,edgeOwner);
 const extend=points=>{for(const [x,y] of points){const right=Math.max(graph.bounds.x+graph.bounds.w,x+45),bottom=Math.max(graph.bounds.y+graph.bounds.h,y+45);graph.bounds.x=Math.min(graph.bounds.x,x-45);graph.bounds.y=Math.min(graph.bounds.y,y-45);graph.bounds.w=right-graph.bounds.x;graph.bounds.h=bottom-graph.bounds.y;}};
 const path=(points,color='#a6b09a',width=1.4,dash='',title='',caption='')=>{
  extend(points);const id=`edge-${labelIndex++}`;
  edgeRecords.push({points,owner:edgeOwner,color,width,dash,title,caption,id});return '';
 };
 for(const family of data.families){
  edgeOwner=`family:${family.id}`;
  const ps=family.parents.map(id=>graph.nodes.get(id)).filter(Boolean),cs=family.children.map(id=>graph.nodes.get(id)).filter(Boolean),familyPrivate=hidePrivate&&(family.private||[...family.parents,...family.children].some(privateHidden));if(!ps.length)continue;
  const primary=ps.some(n=>n.direct)&&cs.some(n=>n.direct),color=primary?'#819273':'#b4bbaa',familyBranchUnconfirmed=family.unconfirmedRelationship||cs.some(c=>unconfirmed.ancestors.has(c.id))||family.parents.some(id=>unconfirmed.roots.has(id));let hx,hy,exitY;
  if(!cs.length){
   if(ps.length>1){const anchor=ps.reduce((a,b)=>a.rank<b.rank?a:b),ax=port(anchor,'top'),ay=above(anchor);
    for(const partner of ps.filter(p=>p!==anchor)){const px=port(partner,'top'),py=above(partner),status=spouseLabel(data,anchor.id,partner.id),caption=familyPrivate?'Личная связь':status.startsWith('гражданск')?'Гражданский брак':status==='партнёр'?'Партнёрство':'Брак';lines.push(path([[ax,anchor.y],...route([ax,ay],[px,py]),[px,partner.y]],'#82917b',1.5,'',familyPrivate?'Личная семейная связь':`${shownName(partner.id)} — ${caption}`,caption));}}
   edgeIndex++;continue;
  }
  const sorted=[...ps].sort((a,b)=>a.x-b.x),a=sorted[0],b=sorted[sorted.length-1];
  const adjacent=ps.length===2&&a.rank===b.rank&&![...graph.nodes.values()].some(n=>!ps.includes(n)&&n.rank===a.rank&&n.x>a.x&&n.x<b.x);
  if(adjacent){
   hx=(a.x+a.w+b.x)/2;hy=a.y+a.h/2;exitY=below(a);
   lines.push(path([[a.x+a.w,hy],[b.x,hy]],color,1.5,'',familyPrivate?'Личная семейная связь':family.events.filter(e=>!hidePrivate||!e.private).map(e=>`${EVENT_LABELS[e.tag]}: ${dateRu(e.date)}`).join('; ')||'Супружеская / семейная связь'));
  }else{
   const anchor=ps.reduce((a,b)=>a.rank>b.rank?a:b);hx=ps.length===1?anchor.x+anchor.w/2:port(anchor,'bottom');hy=exitY=below(anchor);
   for(const p of ps){const px=ps.length===1?p.x+p.w/2:port(p,'bottom'),py=below(p),points=[[px,p.y+p.h],...route([px,py],[hx,hy])];lines.push(path(points,familyBranchUnconfirmed?'#a76552':color,1.4,familyBranchUnconfirmed?'8 6':'',familyBranchUnconfirmed?'Родство не подтверждено':'Семейная связь',ps.length>1?'Семья':''));}
  }
  if(ps.length>1)markers.push({owner:edgeOwner,x:hx,y:hy,color});
  for(const c of cs){
   const links=data.links.filter(l=>l.family===family.id&&l.child===c.id),adopted=links.some(l=>!l.biological),disputed=links.some(l=>l.uncertain),branchUnconfirmed=family.unconfirmedRelationship||unconfirmed.ancestors.has(c.id)||links.some(l=>unconfirmed.roots.has(l.parent)),uncertain=disputed||branchUnconfirmed,shownParentFamilies=data.families.filter(f=>f.children.includes(c.id)&&f.parents.some(id=>graph.nodes.has(id))).length,cx=shownParentFamilies===1?c.x+c.w/2:port(c,'top');
   const caption=disputed?'Спорное родительство':adopted?'Приёмная связь':'',edgeColor=branchUnconfirmed?'#a76552':color,edgeTitle=branchUnconfirmed?'Родство не подтверждено':familyPrivate?'Личная семейная связь':caption||ps.map(n=>shownName(n.id)).join(' + ')+' → '+shownName(c.id);
   let points;
   if(c.rank===Math.max(...ps.map(p=>p.rank))+1)points=[[hx,hy],[hx,exitY],[cx,exitY],[cx,c.y]];
   else points=[[hx,hy],...route([hx,exitY],[cx,above(c)]),[cx,c.y]];
   lines.push(path(points,edgeColor,primary?1.8:1.35,uncertain?'8 6':'',edgeTitle,familyPrivate?'':caption));
  }edgeIndex++;
 }
 const laneChanges=optimizeFamilyLanes(edgeRecords,plan.laneRows);
 const assocSeen=new Set();for(const p of data.people.values()){
  const a=graph.nodes.get(p.id);if(!a)continue;
 for(const assoc of p.associations){
   if(onlyDirect&&(!showGodparents||!sets.direct.has(p.id)||!isGodparentRelation(assoc.relation)))continue;
   const b=graph.nodes.get(assoc.id);if(!b)continue;
   const associationPrivate=privateHidden(p.id)||privateHidden(assoc.id),caption=associationPrivate?'Личная связь':associationLabel(assoc.relation,data.people.get(assoc.id).sex),key=associationKey(p.id,assoc,data);
   if(assocSeen.has(key))continue;assocSeen.add(key);edgeIndex++;edgeOwner=`association:${key}`;
   const points=associationRoute(a,b,graph.nodes,plan,edgeRecords,edgeOwner,/^Восприем/.test(caption));
   lines.push(path(points,'#9b7147',1.6,'7 5',associationPrivate?'Личная связь':`${shownName(assoc.id)} — ${caption.toLowerCase()} для ${shownName(p.id)}`,caption));
  }
 }
 for(const n of graph.nodes.values()){
  const p=data.people.get(n.id),selected=n.id===focus,noteworthy=p.noteworthy,unconfirmedPerson=p.unconfirmedRelationship,fill=selected?'#28483e':noteworthy?(n.direct?'#eeefd8':'#fbf7e8'):n.direct?'#e9eddc':'#faf9f3',stroke=selected?'#28483e':noteworthy?'#a58a4c':n.direct?'#819273':'#c4cab9',text=selected?'#fffdf2':'#344636';
  let y=29;const name=n.nameLines.map(t=>{const line=`<text x="${n.w/2}" y="${y}" fill="${text}" font-family="Georgia,serif" font-size="${n.direct?17:14}" text-anchor="middle">${esc(t)}</text>`;y+=n.direct?22:19;return line;}).join('');
  const variants=n.variantLines.length?(y+=1,n.variantLines.map(t=>{const line=`<text x="${n.w/2}" y="${y}" fill="${selected?'#c6d4bf':'#778372'}" font-family="Arial,sans-serif" font-size="${n.direct?12:11}" font-style="italic" text-anchor="middle">${esc(t)}</text>`;y+=15;return line;}).join('')):'';y+=4;
  const dates=n.dateLines.map(t=>{const line=`<text x="${n.w/2}" y="${y}" fill="${selected?'#c6d4bf':'#7f8877'}" font-family="Arial,sans-serif" font-size="${n.direct?12:11}" text-anchor="middle">${esc(t)}</text>`;y+=16;return line;}).join('');
  const label=n.relationLines.map((line,i)=>`<text x="${n.w/2}" y="${n.h-13-(n.relationLines.length-1-i)*14}" fill="${selected?'#c4d2b5':'#647456'}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${selected?9:11}">${esc(line)}</text>`).join('');
  const accessible=n.privacyHidden?'Личные данные скрыты':[p.name,...p.nameVariants,shownLifespan(p),relations.labels.get(n.id),noteworthy?'Заслуживает внимания':'',unconfirmedPerson?'Родство не подтверждено':''].filter(Boolean).join(' ');cards.push(`<g class="person-card${noteworthy?' noteworthy-person':''}${unconfirmedPerson?' unconfirmed-person':''}" data-id="${esc(n.id)}" tabindex="0" role="button" aria-label="${esc(accessible)}" transform="translate(${n.x} ${n.y})"><title>${esc(accessible)}</title><rect class="card-bg" x="0" y="0" width="${n.w}" height="${n.h}" rx="4" fill="${fill}" stroke="${stroke}" stroke-width="${noteworthy?2:n.direct?2:1}"/>${noteworthy?`<circle class="noteworthy-mark" cx="${n.w-11}" cy="11" r="3.5" fill="#ad8c48"><title>Заслуживает внимания</title></circle>`:''}${unconfirmedPerson?`<circle class="unconfirmed-mark" cx="11" cy="11" r="3.5" fill="#a76552"><title>Родство не подтверждено</title></circle>`:''}${selected?`<rect x="5" y="5" width="${n.w-10}" height="${n.h-10}" rx="2" fill="none" stroke="#668371" stroke-width=".6"/>`:''}${name}${variants}${dates}${label}</g>`);
 }
 for(const marker of markers)lines.push(`<circle cx="${marker.x}" cy="${laneChanges.get(marker.owner+'|'+marker.y)??marker.y}" r="3" fill="${marker.color}"/>`);
 for(const e of edgeRecords)if(e.caption){edgeLabels.push(`<path id="${e.id}" d="${pathData(labelSegment(e.points))}" fill="none" stroke="none"/><text class="edge-caption" fill="${e.color}" font-family="Arial,sans-serif" font-size="13" dy="-6" text-anchor="middle"><textPath href="#${e.id}" startOffset="50%">${esc(e.caption)}</textPath></text>`);}
 const bridged=bridgePaths(edgeRecords);const connections=edgeRecords.map((e,i)=>`<g class="relationship-line"><title>${esc(e.title)}</title><path class="relationship-stroke" d="${bridged[i]}" fill="none" stroke="${e.color}" stroke-width="${e.width}" stroke-linejoin="round" stroke-linecap="${e.dash?'round':'square'}" ${e.dash?`stroke-dasharray="${e.dash}"`:''}/></g>`).join('');
 $('scene').innerHTML=edgeLabels.join('')+connections+lines.join('')+cards.join('');$('count-all').textContent=data.people.size;$('count-direct').textContent=sets.direct.size;$('visible-count').textContent=`Показано ${visible.size} из ${data.people.size}`;$('view-label').textContent=onlyDirect?(showGodparents?'ПРЯМАЯ ЛИНИЯ + ВОСПРИЕМНИКИ':'ПРЯМАЯ ЛИНИЯ'):'ВСЁ ДРЕВО';$('tree-title').textContent=onlyDirect?(showGodparents?'Предки, потомки и восприемники':'Предки и потомки'):'Семейные связи';$('direct-toggle').setAttribute('aria-checked',String(onlyDirect));$('godparents-toggle').setAttribute('aria-checked',String(showGodparents));$('godparents-toggle').disabled=!onlyDirect;$('godparents-option').classList.toggle('inactive',!onlyDirect);$('privacy-toggle').setAttribute('aria-checked',String(hidePrivate));$('branches-toggle').setAttribute('aria-checked',String(verticalBranches));const p=data.people.get(focus),focusName=shownName(focus),focusLife=shownLifespan(p);$('focus-person').innerHTML=`<span class="avatar">${esc(focusName[0])}</span><span><strong>${esc(focusName)}</strong><small>${esc(focusLife||(privateHidden(focus)?'Запись скрыта':'Даты не указаны'))}</small></span>`;applyCamera();
}
function applyCamera(save=true){if(save&&!restoring&&!isDemo)saveView({filename,focus,onlyDirect,showGodparents,hidePrivate,verticalBranches,camera});$('scene').setAttribute('transform',`translate(${camera.x} ${camera.y}) scale(${camera.k})`);$('zoom-value').textContent=Math.round(camera.k*100)+'%';}
function animateCamera(target,duration=650){const start={...camera},token=++cameraAnimation,started=performance.now(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const step=now=>{if(token!==cameraAnimation)return;const t=reduced?1:Math.min(1,(now-started)/duration),ease=1-Math.pow(1-t,3);camera={x:start.x+(target.x-start.x)*ease,y:start.y+(target.y-start.y)*ease,k:start.k+(target.k-start.k)*ease};applyCamera(t===1);if(t<1)requestAnimationFrame(step);};requestAnimationFrame(step);}
function fit(){cameraAnimation++;const r=$('viewport').getBoundingClientRect(),b=graph.bounds;camera.k=Math.min(1.1,(r.width-55)/b.w,(r.height-155)/b.h);camera.k=Math.max(.002,camera.k);camera.x=r.width/2-(b.x+b.w/2)*camera.k;camera.y=90+(r.height-160)/2-(b.y+b.h/2)*camera.k;applyCamera();}
function zoom(factor,x,y){cameraAnimation++;const r=$('viewport').getBoundingClientRect();x??=r.width/2;y??=r.height/2;const k=Math.min(3,Math.max(.002,camera.k*factor)),ratio=k/camera.k;camera.x=x-(x-camera.x)*ratio;camera.y=y-(y-camera.y)*ratio;camera.k=k;applyCamera();}
function center(){cameraAnimation++;const n=graph.nodes.get(focus),r=$('viewport').getBoundingClientRect();camera.k=1;camera.x=r.width/2-(n.x+n.w/2);camera.y=r.height/2-(n.y+n.h/2);applyCamera();}
function navigateTo(id){const n=graph.nodes.get(id);if(!n)return;const r=$('viewport').getBoundingClientRect(),k=1.35;$('search-results').hidden=true;$('search').value='';animateCamera({k,x:r.width/2-(n.x+n.w/2)*k,y:r.height/2-(n.y+n.h/2)*k});}
function notesHtml(notes,label='Примечания'){return notes?.length?`<div class="record-notes"><strong>${esc(label)}</strong><div class="note">${esc(notes.join('\n\n'))}</div></div>`:'';}
function sourcesHtml(sources,label='Источники'){
 if(!sources?.length)return '';
 return `<section class="record-sources"><h4>${esc(label)} · ${sources.length}</h4>${sources.map(s=>{
  const fields=[['Автор',s.author],['Публикация',s.publication],['Архивный шифр',s.reference],['Дата источника',dateRu(s.date)],['Место',s.place],['Хранилище',s.repository],['Шифр хранения',s.callNumber],['Дата выписки',dateRu(s.citationDate)],['Оценка в GEDCOM',s.quality]];
  const info=fields.filter(([,v])=>v).map(([k,v])=>`<div><b>${esc(k)}:</b> ${esc(v)}</div>`).join('');
  return `<details class="source-record"><summary>${esc(s.title)}${s.page?`<span class="source-page">Страница / запись: ${esc(s.page)}</span>`:''}</summary><div class="source-body">${s.missing?'<p>Описание этого источника отсутствует в файле.</p>':''}${info}${s.texts.length?`<div class="source-excerpt"><b>Текст источника / выписки</b><p>${esc(s.texts.join('\n\n'))}</p></div>`:''}${notesHtml(s.notes,'Примечания к источнику')}${s.id?`<small>${esc(s.id)}</small>`:''}${!info&&!s.texts.length&&!s.notes.length&&!s.missing?'<p>Дополнительные сведения не указаны.</p>':''}</div></details>`;
 }).join('')}</section>`;
}
function eventHtml(e,label){const date=e.date?dateRu(e.date):'Дата не указана',description=[e.place,e.value].filter(Boolean).join('\n');return `<div class="event-record${e.noteworthy?' noteworthy-event':''}"><dt class="event-heading">${esc(label||EVENT_LABELS[e.tag]||e.tag)}${e.type?' · '+esc(e.type):''}</dt>${e.noteworthy?'<span class="noteworthy-badge">Заслуживает внимания</span>':''}<dd><time class="event-date">${esc(date)}</time>${description?`<div class="event-description">${esc(description)}</div>`:''}${notesHtml(e.notes,'Примечания к событию')}${sourcesHtml(e.sources,'Источники события')}</dd></div>`;}
const eventPhase=e=>({BIRT:0,CHR:1,BAPM:1,MARR:50,_MARR:50,_CIVIL:50,_COHAB:50,_PRS:50,DIV:70,DEAT:90,BURI:100}[e.tag]??40);
function showDetails(id){opened=id;const p=data.people.get(id);if(privateHidden(id)){$('details-content').innerHTML='<h2>Личные данные скрыты</h2><div class="relation-label">Запись отмечена тегом PRIV в GEDCOM.</div><p class="note">Отключите «Скрывать личное», чтобы увидеть сведения об этом человеке.</p>';$('details').hidden=false;$('select-person').disabled=true;$('select-person').textContent='Личная запись скрыта';return;}
 const familyList=data.families.filter(f=>f.parents.includes(id)),visibleFamilies=familyList.filter(f=>!hidePrivate||!f.private);let sequence=0;const timeline=[...p.events.filter(e=>!hidePrivate||!e.private).map(e=>({e,label:'',sequence:sequence++})),...visibleFamilies.flatMap(f=>f.events.filter(e=>!hidePrivate||!e.private).map(e=>({e,label:`${EVENT_LABELS[e.tag]||'Событие семьи'} · ${f.parents.filter(x=>x!==id).map(shownName).join(', ')}`,sequence:sequence++})))].sort((a,b)=>dateSortKey(a.e.date)-dateSortKey(b.e.date)||eventPhase(a.e)-eventPhase(b.e)||a.sequence-b.sequence),fields=timeline.map(item=>eventHtml(item.e,item.label)).join('');
 const familyInfo=visibleFamilies.filter(f=>f.notes.length||f.sources.length).map(f=>`<h3>Семья${f.parents.some(x=>x!==id)?' · '+f.parents.filter(x=>x!==id).map(x=>esc(shownName(x))).join(', '):''}</h3>${notesHtml(f.notes,'Примечания к семье')}${sourcesHtml(f.sources,'Источники семьи')}`).join('');
 const relativeList=(label,ids)=>{const shown=[...new Set(ids)].filter(x=>!privateHidden(x)),heading=label?label[0].toLocaleUpperCase('ru')+label.slice(1):'';return shown.length?`<h3>${esc(heading)}</h3>${shown.map(x=>`<button class="relative" data-relative="${esc(x)}">${esc(shownName(x))} <span>↗</span></button>`).join('')}`:'';};
 const path=relations.paths.get(id);$('details-content').innerHTML=`<h2>${esc(p.name)}</h2><div class="relation-label">${esc(relations.labels.get(id))}</div>${p.unconfirmedRelationship?'<p class="note warning">Родство не подтверждено. Линия к потомкам и вся ветвь предков отмечены терракотовым пунктиром.</p>':''}${p.nameRecords.slice(1).map(n=>`<p class="name-variant"><span>${esc(n.label)}:</span> ${esc(n.text)}</p>`).join('')}<dl>${fields}</dl>${notesHtml(p.notes)}${sourcesHtml(p.sources,'Источники о человеке')}${familyInfo}${relativeList('Родители',p.parents.map(l=>l.parent))}${p.spouses.map(other=>relativeList(privateHidden(other)?'Личная связь':spouseLabel(data,id,other),[other])).join('')}${relativeList('Дети',p.children.map(l=>l.child))}${p.associations.map(l=>relativeList(privateHidden(l.id)?'Личная связь':associationLabel(l.relation,data.people.get(l.id).sex),[l.id])+(privateHidden(l.id)?'':notesHtml(l.notes,'Примечания к связи')+sourcesHtml(l.sources,'Источники связи'))).join('')}${path?.length?`<h3>Путь от выбранного человека</h3><p class="note">${esc(shownName(focus))}${path.map(e=>privateHidden(e.id)?'<br>↓ личная связь<br>Личные данные скрыты':`<br>↓ ${esc(e.label)}<br>${esc(e.name)}`).join('')}</p>`:''}${p.parents.some(l=>!l.biological||l.uncertain)?'<p class="note warning">Есть приёмные или спорные родительские связи. Они показаны точечной линией с подписью и не включены в прямую биологическую линию.</p>':''}<p class="technical">${esc(p.id)} · одна карточка на человека</p>${data.warnings.length?`<details><summary>Замечания к файлу (${data.warnings.length})</summary><p class="note warning">${esc(data.warnings.join('\n'))}</p></details>`:''}${graph.exceptions?'<p class="note">Поколения отсчитываются от выбранного человека. Для повторных предков используется ближайший путь; межпоколенные связи сохранены.</p>':''}<details><summary>Исходная запись GEDCOM</summary><pre>${esc(rawText(p.raw))}</pre></details>`;$('details').hidden=false;$('select-person').disabled=id===focus;$('select-person').textContent=id===focus?'Уже выбран главным':'Выбрать главным человеком';}
function rawText(n,level=0){return `${level} ${n.id?n.id+' ':''}${n.tag} ${n.value}\n`+n.children.map(c=>rawText(c,level+1)).join('');}
function setFocus(id){focus=id;$('details').hidden=true;$('search-results').hidden=true;$('search').value='';recalculate();if(onlyDirect)fit();else center();}
$('upload').onclick=()=>$('file').click();$('dismiss-error').onclick=()=>$('import-dialog').close();
async function importFile(file){if(!file)return;const old=$('upload').textContent;$('upload').disabled=true;$('upload').textContent='Читаем файл…';await new Promise(r=>setTimeout(r,30));try{const bytes=new Uint8Array(await file.arrayBuffer());let text;const head=new TextDecoder('windows-1251').decode(bytes.slice(0,5000));if(bytes[0]===255&&bytes[1]===254)text=new TextDecoder('utf-16le').decode(bytes);else if(bytes[0]===254&&bytes[1]===255)text=new TextDecoder('utf-16be').decode(bytes);else if(/1 CHAR (ANSEL|MACINTOSH)/i.test(head))throw new Error('Этот файл использует старую кодировку. Экспортируйте GEDCOM в UTF-8 и загрузите его снова, чтобы сохранить все буквы имён.');else if(/1 CHAR (ANSI|WINDOWS-1251|CP1251)/i.test(head))text=new TextDecoder('windows-1251').decode(bytes);else{try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{text=new TextDecoder('windows-1251').decode(bytes);}}load(text,file.name);try{await savedGedcom('write',{text,name:file.name});}catch{toast('Древо открыто, но браузер не разрешил сохранить файл. После перезагрузки потребуется загрузить его снова.');return;}toast(`Открыто ${data.people.size} людей. Все записи включены в древо.${data.warnings.length?' Есть замечания к данным.':''}`);}catch(e){$('import-error').textContent=e.message;$('import-dialog').showModal();}finally{$('upload').disabled=false;$('upload').textContent=old;$('file').value='';}}
$('file').onchange=e=>importFile(e.target.files[0]);
$('direct-toggle').onclick=()=>{onlyDirect=!onlyDirect;$('search').value='';$('search-results').hidden=true;render();fit();};$('godparents-toggle').onclick=()=>{if(!onlyDirect)return;showGodparents=!showGodparents;$('details').hidden=true;$('search').value='';$('search-results').hidden=true;render();fit();};$('privacy-toggle').onclick=()=>{hidePrivate=!hidePrivate;$('details').hidden=true;$('search').value='';$('search-results').hidden=true;render();};$('branches-toggle').onclick=()=>{verticalBranches=!verticalBranches;render();fit();};$('focus-person').onclick=()=>showDetails(focus);$('close-details').onclick=()=>$('details').hidden=true;$('select-person').onclick=()=>setFocus(opened);
$('details-content').onclick=e=>{const button=e.target.closest('[data-relative]');if(button)showDetails(button.dataset.relative);};
$('search').oninput=()=>{const q=$('search').value.trim().toLocaleLowerCase('ru');if(!q){$('search-results').hidden=true;return;}const tokens=q.split(/\s+/),matches=[...graph.nodes.keys()].map(id=>data.people.get(id)).filter(p=>!privateHidden(p.id)&&tokens.every(t=>p.names.join(' ').toLocaleLowerCase('ru').includes(t)||p.id.toLowerCase().includes(t)));$('search-results').innerHTML=matches.length?matches.slice(0,100).map(p=>`<button data-person="${esc(p.id)}">${esc(p.name)}<small>${esc([shownLifespan(p),relations.labels.get(p.id)].filter(Boolean).join(' · ')||p.id)}</small></button>`).join('')+(matches.length>100?'<p class="note">Уточните имя: показаны первые 100 совпадений.</p>':''):'<p style="padding:12px;font-size:13px">Среди показанных людей совпадений нет</p>';$('search-results').hidden=false;};
$('search-results').onclick=e=>{const p=e.target.closest('[data-person]');if(p)navigateTo(p.dataset.person);};$('search').onkeydown=e=>{if(e.key==='Escape')$('search-results').hidden=true;if(e.key==='Enter')$('search-results').querySelector('button')?.click();};
$('zoom-in').onclick=()=>zoom(1.25);$('zoom-out').onclick=()=>zoom(.8);$('fit').onclick=fit;$('center').onclick=center;
const pointers=new Map();let moved=false,lastClick=0;
$('viewport').addEventListener('pointerdown',e=>{if(e.button!==0)return;cameraAnimation++;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=false;$('viewport').setPointerCapture(e.pointerId);});
$('viewport').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const before=[...pointers.values()],old=pointers.get(e.pointerId),dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const after=[...pointers.values()],dist=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),r=$('viewport').getBoundingClientRect();const oldDist=dist(before);if(oldDist>0)zoom(dist(after)/oldDist,(after[0].x+after[1].x)/2-r.left,(after[0].y+after[1].y)/2-r.top);}else{camera.x+=dx;camera.y+=dy;applyCamera();}});
$('viewport').addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(!moved){const card=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-id]');if(card){showDetails(card.dataset.id);lastClick=Date.now();}}});$('viewport').addEventListener('pointercancel',e=>pointers.delete(e.pointerId));
$('viewport').addEventListener('wheel',e=>{e.preventDefault();const r=$('viewport').getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
$('viewport').addEventListener('keydown',e=>{const card=e.target.closest('[data-id]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();showDetails(card.dataset.id);return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();camera.x+=e.key==='ArrowLeft'?60:e.key==='ArrowRight'?-60:0;camera.y+=e.key==='ArrowUp'?60:e.key==='ArrowDown'?-60:0;applyCamera();}if(e.key==='+'||e.key==='=')zoom(1.25);if(e.key==='-')zoom(.8);if(e.key==='0')fit();});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('details').hidden=true;});
let dragDepth=0;document.addEventListener('dragenter',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();dragDepth++;$('drop-overlay').hidden=false;}});document.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;$('drop-overlay').hidden=true;}});document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('drop-overlay').hidden=true;importFile(e.dataTransfer.files[0]);});
$('export').onclick=()=>{const b=graph.bounds,svg=`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${Math.ceil(b.w)}" height="${Math.ceil(b.h+90)}" viewBox="${b.x} ${b.y-90} ${b.w} ${b.h+90}"><rect x="${b.x}" y="${b.y-90}" width="${b.w}" height="${b.h+90}" fill="#f4f3ec"/><text x="${b.x+40}" y="${b.y-35}" font-size="27" font-family="Georgia" fill="#28483e">Родословная · ${esc(shownName(focus))}</text><text x="${b.x+40}" y="${b.y-8}" font-size="14" font-family="Arial" fill="#718166">${onlyDirect?'Прямая линия':'Все люди'} · ${graph.nodes.size} из ${data.people.size} · крупные карточки — прямая линия${onlyDirect&&showGodparents?' · восприемники показаны':''}${hidePrivate?' · личное скрыто':''}${verticalBranches?' · ветки вверх':''}</text>${$('scene').innerHTML}</svg>`;const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Родословная.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Векторное древо сохранено. Его можно масштабировать без потери качества.');};
let previousViewport;new ResizeObserver(entries=>{const rect=entries[0].contentRect;if(previousViewport&&graph){camera.x+=(rect.width-previousViewport.width)/2;camera.y+=(rect.height-previousViewport.height)/2;applyCamera();}previousViewport={width:rect.width,height:rect.height};}).observe($('viewport'));
try{
 const saved=await savedGedcom(),view=readView();
 if(saved?.text){load(saved.text,saved.name);if(view?.filename===saved.name){if(data.people.has(view.focus))focus=view.focus;onlyDirect=!!view.onlyDirect;showGodparents=!!view.showGodparents;hidePrivate=!!view.hidePrivate;verticalBranches=!!view.verticalBranches;recalculate();if(view.camera&&['x','y','k'].every(k=>Number.isFinite(view.camera[k]))&&view.camera.k>0){camera=view.camera;applyCamera();}else fit();}}
 else load(demo,'Пример семейного древа',true);
}catch{load(demo,'Пример семейного древа',true);}
restoring=false;
